### PR TITLE
[WiP] Update to 3.18

### PR DESCRIPTION
**Pull request by Bubu**
I started merging the changes seperately like @thermatk did before. I think this is a real benefit for reviewing.
Of course we won't achieve a useful state after every commit, but I guess it's still better this way.

I think I'll try and see how far I get with this before deciding to merge the changes in this fashion or as a single blob and then do the fixups later.

@thermatk I commited the changes with the `--author` option of git to properly attribute them. What do you think of this approach?

### CODE REVIEW

**Comment by thermatk** [comment]
i think it'll take time, because you'll have to resolve all the merge conflicts I already resolved in #136 
and 1by1 is only needed for review
Yet for an easy review I have already done the 1by1 here: https://github.com/thermatk/Telegram-FOSS/commits/original3.13-to-3.18 , and even reviewed and crossed out a lot of things.
I don't know, honestly :+1: 
In #136 I have just merged the big drop, resolved conflicts and made some fixes and changes

**Comment by Bubu** [comment]
I have taken your branch as a baseline and I'm working through it. But I wanted to reorder the commits a bit.
I'll be adding your review  comments as I go, just leaving out the [safe] tags.

The one benefit of doing it this way is that the browser will not die when viewing the changes in github. :-)

**Comment by thermatk** [comment]
Haha, then you also need to take into account that this branch is going from upstream 3.13 to upstream 3.18.
From there to FOSS you either have to take my "reapply patches from scratch" approach from branch https://github.com/thermatk/Telegram-FOSS/commits/3.18-to-3.18-foss
or #136 conflict resolution and fixes on top.
The resulting source code will actually be the same, that was intended :+1:

**Comment by Bubu** [comment]
As a last action in this series I wanted to do a 'fake' merge. Which tells git the DrKLO 3.18 commit was merged properly but not taking *any* changes from this commit. 
`git merge --no-commit && git checkout --ours .`  (I need to verify this).
This is quite hacky and that's why I wanted to try this out before commiting anything properly. :-)

But if it works it should land us in the desired state with a proper step by step merge process...

**Comment by thermatk** [comment]
For me, the last commit is a NON fake merge, because that was the easiest way to activate the submodule
https://github.com/thermatk/Telegram-FOSS/commit/574e9d3023188d18c5a4cfa858e14271bfb00449

**Comment by thermatk** [comment]
The problem of lost branches is easily fixable - just merge #136 to master here for functional state and #133, or just the review commits, to a separate branch, also in this repo.

**Comment by thermatk** [comment]
Accept #138 and immediately afterwards this one and it is finally done!

**Comment by Matttter** [comment]
Great work guys, now soon my friends can stop bugging me to "fix my Telegram" when they try to call me :laughing:

**Pull request merged**
