### PR TITLE
build_libvpx_clang: make it use api 16 for 32-bit targets

### PR DESCRIPTION
**Pull request by nift4**
thanks for this project :)

compiling tested directly with this, running on device as well, though inside my fork and not just with this patch

### CODE REVIEW

**Comment by thermatk** [comment]
hi @nift4 
what is the reason behind it? Upstream compiles with 21 just fine. Also, why did you remove the extra cflags?

**Comment by nift4** [comment]
The reason is that android-21 binaries obviously won't run before API 21, and the minSdk of Telegram for Android is 16. The extra cflags caused a build error and according to google aren't supposed to be used.

**Comment by nift4** [comment]
@thermatk 
ps: upstream probably broke pre-lollipop devices, i tested my fork on kitkat and it works

**Comment by thermatk** [comment]
I don't want to break post-lollipop devices, so I'm starting the emulator
AFAIK compiling with 21 doesn't automatically mean it doesn't work below 21

**Comment by thermatk** [comment]
Can't make a call because emulator has problems with audio capture
but there is no native error
how did it fail for you?

**Comment by thermatk** [comment]
made a couple calls from kitkat emulator
all works well
see no reason to divert and risk with the majority of the population

**Comment by nift4** [comment]
with or without the patch? in either case thanks for the note, seems like this is useless then
it didn't fail for me i just addressed a todo in an old version of the build script

**Pull request closed without merging**
