### PR TITLE
Option to hide sponsored messages

### PR DESCRIPTION
**Pull request by ma5ter**

### CODE REVIEW

**Comment by flexagoon** [comment]
@ma5ter this violates the Telegram API ToS. If a client doesnt show sponsored messages, then the API key will be banned and the client will be unusable.

**Comment by eternal-sorrow** [comment]
@flexagoon There should have some way to circumvent this. For example give user an option to enter his own api key and only then unlock an option to hide the ads.

**Comment by thermatk** [comment]
Telegram-FOSS project is not here to circumvent anything :)

**Comment by Younes-L** [comment]
> @flexagoon There should be some way to circumvent this. For example give the user an option to enter his own api key and only then unlock an option to hide the ads.

Try NekoX client, it has exactly what you described : an option for users to enter their own API key

**Comment by eternal-sorrow** [comment]
That's a shame

**Comment by eternal-sorrow** [comment]
>Telegram-FOSS project is not here to circumvent anything :)

This is a shame

**Comment by eternal-sorrow** [comment]
@Younes-L Is it open source? Is it available through f-droid?

**Comment by Younes-L** [comment]
@eternal-sorrow yes and yes https://f-droid.org/packages/nekox.messenger/

**Comment by flexagoon** [comment]
@Younes-L I am already using NekoX, and it has ads. Do they automatically get disabled if I use my own API key?

**Comment by Younes-L** [comment]
> @Younes-L I am already using NekoX, and it has ads. Do they automatically get disabled if I use my own API key?

No, the client does not hide ads at all , but you can use your API key if you want

**Comment by eternal-sorrow** [comment]
@Younes-L It actually has an option to hide ads if you use custom API, but it's disabled by default.

**Comment by Younes-L** [comment]
> @Younes-L It actually has an option to hide ads if you use custom API, but it's disabled by default.

Are you sure ? ;) that must be some other client, definitely not nekoX ;) ;)

**Comment by eternal-sorrow** [comment]
>Are you sure ? ;)

Positive. `Settings -> Neko Settings -> General -> Hide sponsored messages`. Fun fact is that it works even if you use oficial Telegram Android key.

**Comment by bodqhrohro** [comment]
@flexagoon
> then the API key will be banned

Do you base this on any evidence?

AFAIK, ToS violations just lead to banning apps from app stores, which barely applies to free software that is not published this way.

**Comment by JustAnUserLol** [comment]
@bodqhrohro tg foss has agreement with tg

**Comment by flexagoon** [comment]
@bodqhrohro 

> Do you base this on any evidence?

Yes, that's an official statement from Telegram

**Comment by bodqhrohro** [comment]
@flexagoon any quotation, please?

I know only about [this](https://core.telegram.org/api/sponsored-messages):
> Unfortunately, Telegram cannot financially sustain third-party apps that do not display sponsored messages and they will have to be disconnected. 

Nothing about banning the API keys.

**Comment by escape0707** [comment]
@bodqhrohro https://core.telegram.org/api/terms

**Comment by bodqhrohro** [comment]
> Just try to get an API key

I have it for years, dude.

I'm asking about *de facto*, not *de jure*, and surely not about *de jure* wrapped in far-fetched assumptions. "we will have to discontinue your access to Telegram API" can mean anything in reality. Also, how are apps that don't ship id/hash with themselves and require a user to obtain their own ones can be "discontinued" this way?

**Comment by escape0707** [comment]
Then you can just use your own API key and try what will happen. It could be nothing, but also a shadow-ban for the API key and the account applied it. Good luck.

I'm okay with an always updated fork, patch, or AUR PKGBUILD to not display the sponsored messages. But if this repo's maintainers don't like to do it, I can understand that, too.

**Comment by bodqhrohro** [comment]
@escape0707 I run into such assumptions for years, and suspect them as a deliberately boosted hysteria, unless any practical cases are provided. F. e., people complained for being banned for backup apps the same way, and then it turned out the actual reason was other suspicious activity from their accounts, thus they just gave a false intimidation for other users. Please don't spread a baseless panic.

**Comment by couleurm** [comment]
> @ma5ter this violates the Telegram API ToS. If a client doesnt show sponsored messages, then the API key will be banned and the client will be unusable.

How does it detect what's shown on the client?

**Comment by bodqhrohro** [comment]
> How does it detect what's shown on the client?

A client is expected to send certain updates while a user interacts with an ad.

**Pull request closed without merging**
