### PR TITLE
[TF] set sane default location and zoom level

### PR DESCRIPTION
**Pull request by Bubu**
This fixes two things:

* actually set the default location in case location permissions are
granted but non-of the location providers can supply a location for now.
* set a sane zoomlevel for the default location, otherwise you end up
with a grey screen in the saharan desert and first need to zoom out a
few-thousand km.

### CODE REVIEW

**Comment by Bubu** [comment]
@thermatk If you agree I can also fold that into the general `replace Google Maps with OSMDroid` commit.

**Comment by Bubu** [comment]
before:
image

after:
image

**Comment by Bubu** [comment]
I just noticed in the pictures there seems to be one side-effect to this: It now says accurate to 0 m instead of 'loading' about your current location...

**Comment by thermatk** [comment]
That's not good, so you set a user location like it's loaded, when it isn't?

**Comment by Bubu** [comment]
> That's not good, so you set a user location like it's loaded, when it isn't?

it's actually the same behaviour you get when not allowing Telegram to access your location at all. That's handled not too well it seems.

**Comment by thermatk** [comment]
Would be better to check for null around here:
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/21792656a237408ad452f4680c3934c8cf3ebf88/TMessagesProj/src/main/java/org/telegram/ui/LocationActivity.java#L788
and if null, zoom the map to Paris or whatever wins
but not position a marker

**Pull request closed without merging**
