### PR TITLE
gradle: remove custom minsdk

### PR DESCRIPTION
**Pull request by Bubu**
This was never set for the fat flavour either.

closes https://github.com/Telegram-FOSS-Team/Telegram-FOSS/issues/345

### CODE REVIEW

**Comment by Bubu** [comment]
Why not merge this? Without this users of older Androids only get the fat apk. And those are probably in need of disk space the most.

**Comment by thermatk** [comment]
Why not build 1,2 and 5 then?

**Comment by Bubu** [comment]
I don't know. But the afat flavour we build also uses the _SDK23manifest as well and doesn't set a minsdk either.

**Comment by thermatk** [comment]
Just in case, fdroiddata request was changed :)

**Pull request closed without merging**
