### PR TITLE
Switch DNS from Google & Cloudflare to LibreDNS & Snopyta

### PR DESCRIPTION
**Pull request by Nex8192**

### CODE REVIEW

**Comment by kaliangel** [comment]
It would be nice to get that PR accepted.  These changes are important to improve confidentiality.  It is contradictory to fork Telegram to remove some trackers and still use Google or Cloudflare DNS.

**Comment by thermatk** [comment]
It makes approx. 0 sense. It's not there to DNS :wink:

**Comment by anupritaisno1** [comment]
This is just stupid. By doing so you actually make yourself stand out more

Not to add:
Commit isn't even documented, just comments a bunch of stuff without explanation and one of the commits isn't even in English

This isn't maintainable whatsoever. Do you really expect this to be merged?

**Comment by Nex8192** [comment]
Do you really want me to comment the 2 lines I edited ?...

**Comment by PEPERSO** [comment]
Hello,

> It makes approx. 0 sense. It's not there to DNS wink

Ok, I've seen you saying that in previous issues, but then, could you please explain why it is here ? 
Several users have noticed connexions from Telegram-FOSS to :
* `dns.google.com` (even if, I've understood, it's not for dns purposes)
* `google.ru`
* `www.google.com`
* `mozilla.cloudflare.com` (in case calls to googles dns have no response)

If it is not for DNS, I don't understand why these calls even exist. I know Telegram does not use dns to get and send messages, but some users told me that these calls were used to accelerate webpage rendering. Moreover for FOSS convinced people, why not trying to replace connexions to absolutely non foss (or privacy respecting) services by others ? I mean, it is not for DNS, okay, but why not replace them, since it is contradictory with the objective of this fork ?

I love using your app and thank you for the time you're taking to remove non foss parts of Telegram, but I really don't understand this point and why you keep refusing to remove those calls to google and cloudflare. 
I hope you understand our point and we can make a constructive discussion about it.

**Comment by varistov** [comment]
It is just to circumvent censorship

**Comment by PEPERSO** [comment]
I get that, but still, do you really think it could not pass through any other place than google ? I mean it is unlikely a country blocks libre dns and synopta. They are not famous, and there's nothing special about them... And there could be other fallbacks in case these are blocked
Or even use google as fallback (if really you need it), but start trying with others if possible... Anything absurd in what I say ?

**Comment by varistov** [comment]
Google and amazon are commonly used for domain fronting. To block the service that use domain fronting, they have to block amazon and google completely, which breaks the internet

**Comment by varistov** [comment]
Maybe Telegram could implement this only for users who are from countries that censor Telegram, but who knows your country might block telegram without any prior notice one fine day

**Comment by PEPERSO** [comment]
Okay, I get that, but still, I think google could only be a fallback, or an option. With several fallback, ending with google or cloudflare, it is absolutely certain that the request will reach at least one server.

I'm just saying google and cloudflare have nothing in common with FOSS ethic, and they should defenetly not be used by default here, since there are FOSS and privacy respecting alternatives and they can still be used as a security fallback...

**Pull request closed without merging**
