### PR TITLE
[TF][FEATURE] Added ability to mute dialog from context menu in dialogs.

### PR DESCRIPTION
**Pull request by 23rd**
This PR allows users to mute notifications without opening a dialog activity.
The code is compatible with 5.3.1 version.

image

### CODE REVIEW

**Comment by 23rd** [comment]
Rebased on top of latest master branch.

**Comment by thermatk** [comment]
wait, it's not ready yet :rofl:

**Comment by 23rd** [comment]
Okay. 😄

**Comment by 23rd** [comment]
After the last update, this PR now makes no sense.

**Pull request closed without merging**
