### PR TITLE
Added complete Czech language translation - 4.1.1.

### PR DESCRIPTION
**Pull request by JimmyS83**
All correction and also spell checks was done. Translation is coherent across my czech translations of Android Telegram, Telegram Desktop, Plus Messenger and Telegram-FOSS.

Signed-off-by: Jiri Spicak jiri.spicak@mail.ru (github: JimmyS83)

### CODE REVIEW

**Comment by JimmyS83** [comment]
Didnt noticed, that DrKLO released newer version.  Ill try to create some email alarms through github.

**Comment by JimmyS83** [comment]
I started maintain repository only for Czech language: https://github.com/JimmyS83/telegram-cz-translation. Is there a way, how you can add Czech language from there automatically? The format of .xml file is practically identicall with Android's one (https://raw.githubusercontent.com/JimmyS83/telegram-cz-translation/master/android_cz.xml).

If you would need anything from my side, just ping me please.

**Comment by thermatk** [comment]
@JimmyS83 you see how crazy it is and I don't really think including unofficial translations together with official is the best way
Probably, a better way would be to bundle them in assets or something and include in the way the unofficial ones are "applied" from chats? This would also lessen the requirements for correctness and coverage of the translation files

**Comment by JimmyS83** [comment]
I dont know what you mean by "bundle them". Official clients **fortunatelly** still ofers load custom language (its described in http://telegram.zde.cz). So the "bundle" as I understand it is just file, in that case from Github.

Reasons, why they didnt accept any other language officially are well hidden from me, but I think there arent any in this fork. So basically I am asking, what its need to be done from my side, to include Czech in FOSS version again :)

If you decide to stick with the official bundled languages, it is your call and your right, and I will respect that. Drawback of custom languages is, that the procedure, how to load them, is hidden, and not mentioned anywhere in the app. So for "usual users" is almost impossible to know, that they can have Telegram in own language.  Must say that FOSS users will be more experienced, but still, I dig this information about custom language on some 3rd Party forum, not Telegram pages itself..

**Comment by thermatk** [comment]
@JimmyS83 my proposal is to not abuse and mix additional languages with official ones, as it affects the build quality directly, but to use this:

https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/TMessagesProj/src/main/java/org/telegram/messenger/LocaleController.java#L445

This must be the function used for the loading of unofficial files sent through messages. Shouldn't be hard to add a folder in the assets with a lot of xmls, requirements for which will be less strict, and add a one-time loading function or an additional button to activate them in settings

**Pull request closed without merging**
