### PR TITLE
build.gradle: also build armeabi version

### LINKED ISSUE #178: ARMv6 (armeabi) support
Previously telegram client has support for armv6 devices (armeabi platform).
I can see armeabi references is still in code.

Is it possible to enable support of armeabi platform in FOSS telegram client?

### PR DESCRIPTION
**Pull request by Bubu**
Closes #178

### CODE REVIEW

**Comment by thermatk** [comment]
I would expect calls to miserably fail with 99% prob, and not even be sure about other functionality
Upstream killed armv6 when they worked with jni to prepare for voip support

**Comment by Bubu** [comment]
@thermatk All native code compiles fine for armeabi so I'd guess it should just  work fine. 
(Okay, I didn;t check for any new warnings but that's a bit cumbersome because all telegram native code generates hundreds of those anyway.)

AFAIK armeabi just supports a reduced instruction set compared to it's v7 variant. As the native code doensn't contain any assembly (well openssl does but their build-system should be able to devide whether they can use that or not) it should just work when compiled with the armebi target.

AFAIK there are no armeabi emulator images available so someone would need to test this with a real device.

**Comment by Bubu** [comment]
But maybe upstream killed it for a reason and it will indeed be broken by a subtle compiler bug or something... who knows.

**Comment by Bubu** [comment]
@thermatk will you merge this for the next release?

**Comment by thermatk** [comment]
https://github.com/Telegram-FOSS-Team/Telegram-FOSS/commit/4f699003ef569ccfe8202edd31540d56c23493aa

**Comment by ildar** [comment]
Would be a super feature supporting old HW when commercial version doesn't

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Pull request closed without merging**
